# -*- coding: utf-8 -*-
"""
Created on Sun Jul  6 21:58:23 2025

@author: Lab
"""

import shutil
import os

path = r"Z:\Lilli\sept 12 NBDY smFISH\to quant\bigFISH_In"
Conditions = [
#               "DMSO_CT",
#               "DMSO_HS",
#               "DMSO_2HR",
#               "DMSO_3HR",
#               "DMSO_4HR",
#               "DMSO_6HR",
#               "DMSO_8HR",
#               "HRN_CT",
#               "HRN_HS",
#               "HRN_2HR",
#               "HRN_3HR",
#               "HRN_4HR",
#               "HRN_6HR",
#               "HRN_8HR",
#               "Puro_CT",
#               "Puro_HS",
#               "Puro_2HR",
#               "Puro_3HR",
#               "Puro_4HR",
#               "Puro_6HR",
#               "Puro_8HR",             
              # "ActD+HS_HS", 
              # "ActD+HS_3HR", 
              # "ActD+HS_6HR", 
              # "ActD+HS_9HR", 
              # "ActD+HS_12HR",
              # "CT+ActD_CT",
              # "CT+ActD_3HR",
              # "CT+ActD_6HR",
              # "CT+ActD_9HR", 
              # "CT+ActD_12HR",
              #"HS+ActD_3HR",
              #"HS+ActD_6HR",
              #"HS+ActD_9HR",
              #"HS+ActD_12HR",
              #"HS+ActD_HS", 
              # "MEFs Hsp90AB_CT",
              # "MEFs Hsp90AB_24HR",
              # "MEFs Hsp110_CT",
              # "ROSA_CT",
               # "CT",
              #  "HS",
              #  "2HR",
              #  "3HR",
              #  "4HR",
#                "6HR",
             #   "8HR",
              #  "10HR",
              #  "12HR",
              #  "24HR",
              # "2H_R",
              # "3H_R",
              # "4H_R",
              # "6H_R",
              # "8H_R",
              # "10H_R",
              # "12H_R",
              # "24H_R",
              # "DTreat_4rec",
              # "DTreat_6rec",
              # "DTreat_8hrec",
              # "DTreat_10hrec",
              # "DTreat_12hrec",
              # "DTreat_24hrec",
              # "DTreat_Ctrl",
              # "Treat_2hrec",
              # "Treat_3hrec",
              # "Treat_4hrec",
              # "Treat_6hrec",
              # "Treat_8rec",
              # "Treat_10rec",
              # "Treat_12rec",
              # "Treat_24rec",
              # "Treat_ctrl",
              # "Treat_HS",
              # "MEFs WT_50ng_15H_Dox+",
              # "MEFs WT_50ng_15H_Dox-",
              # "NBDY_50ng_15H_Dox+",
              # "NBDY_50ng_15H_Dox-",
              # "MEFs WT_100ng_15H_Dox+",
              # "MEFs WT_100ng_15H_Dox-",
              # "NBDY_100ng_15H_Dox+",
              # "NBDY_100ng_15H_Dox-",
              # "MEFs WT_100ng_8H_Dox+",
              # "MEFs WT_100ng_8H_Dox-",
              # "NBDY_100ng_8H_Dox+",
              # "NBDY_100ng_8H_Dox-",
              # "MEFs WT_100ng_24H_Dox+",
              # "MEFs WT_100ng_24H_Dox-",
              # "NBDY_100ng_24H_Dox+",
              # "NBDY_100ng_24H_Dox-",
              'NB DOX - cntl 4h',
              'NB DOX + cntl 4h',
              'NBDY DOX- 4h',
               'NBDY DOX+ 4h',
               'WT DOX + cntl',
               'WTDOX+ 4h',
               ]

for folder in Conditions:
    os.mkdir(os.path.join(path,folder))
    for file in os.listdir(path):
        if folder in file and os.path.isfile(os.path.join(path,file)):
            shutil.move(os.path.join(path, file), os.path.join(path,folder,file))
            
